# Generated by Django 5.1.6 on 2026-02-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_market_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='food_type',
            field=models.CharField(choices=[('Фр', 'Фрукты'), ('Ов', 'Овощи'), ('Зел', 'Зелень'), ('Сл', 'Сладкое'), ('Мяс', 'Мясо')], default=3, max_length=100),
            preserve_default=False,
        ),
    ]
