# Generated by Django 5.1.6 on 2026-02-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_market_app', '0002_good_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='image2',
            field=models.ImageField(default='none', upload_to=''),
        ),
    ]
