# Generated by Django 5.1.6 on 2026-03-14 07:20

import goods_market_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_market_app', '0003_good_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(default='none', upload_to=goods_market_app.models.Good.user_directory_path),
        ),
        migrations.AlterField(
            model_name='good',
            name='image2',
            field=models.ImageField(default='none', upload_to=goods_market_app.models.Good.user_directory_path),
        ),
    ]
