# Generated by Django 5.1.6 on 2026-03-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_market_app', '0004_user_alter_good_image_alter_good_image2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
