# Generated by Django 6.0.3 on 2026-04-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_market_app', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='good',
            name='food_type',
            field=models.CharField(choices=[('fruits', 'Фрукты'), ('vegetables', 'Овощи'), ('greenery', 'Зелень'), ('sweets', 'Сладкое'), ('meat', 'Мясо')], max_length=100),
        ),
    ]
